"""yandex id added to user

Revision ID: 7803f28a9662
Revises: 18bf164d1f98
Create Date: 2025-03-31 07:04:40.679279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7803f28a9662'
down_revision: Union[str, None] = '18bf164d1f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'audio_files', ['id'])
    op.add_column('users', sa.Column('yandex_id', sa.String(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_yandex_id'), 'users', ['yandex_id'], unique=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_yandex_id'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'yandex_id')
    op.drop_constraint(None, 'audio_files', type_='unique')
    # ### end Alembic commands ###
